# -*- coding: utf-8 -*-
"""Stock_index.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/199z1-jqyzeox2Pee_8QN2HnSFSOCkOzy
"""

#! pip install yfinance

import pandas as pd
import pandas_gbq
import numpy as np
import yfinance as yf
from datetime import date
from datetime import timedelta
from google.cloud import bigquery
import pytz
from pandas.io import gbq
import matplotlib.pyplot as plt
from sklearn import linear_model

if __name__ == "__main__":

    sql_dji = 'select * from `bigdata6893-328419.stock_data.DJI`'
    sql_spc = 'select * from `bigdata6893-328419.stock_data.SPC`'
    sql_xic = 'select * from `bigdata6893-328419.stock_data.XIC`'
    df_dji= pandas_gbq.read_gbq(sql_dji)
    df_spc= pandas_gbq.read_gbq(sql_spc)
    df_sic= pandas_gbq.read_gbq(sql_xic)

    df_dji['Delta'] = df_dji['Close'] - df_dji['Open']
    df_dji['Delta_class'] = df_dji['Delta'].apply(lambda x: 1 if x>0 else 0)

    df_dji.round(2)
