# -*- coding: utf-8 -*-
"""sentiment_analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TmtJw14FIBvr38ncTLQ22a_OWtbXK_xt
"""

import pandas as pd
import pandas_gbq

stream_data = pandas_gbq.read_gbq(
    'SELECT * FROM `bigdata6893-328419.twitterstream` WHERE stream_date = CURDATE()',
    project_id = 'bigdata6893-328419'
)

from google.colab import drive

if __name__ == '__main__':

    drive.mount('/content/gdrive')

    model_save_name = 'sentiment_lstm.pt'
    path = F'/content/gdrive/My Drive/Fall 2021/EECS6895-BDA/Final Project/{model_save_name}'
    model_lstm = tf.keras.models.load_model(path)

    predictions_lstm = model_lstm.predict(streamed_tweets)

    positive_lstm = [1 for x in predictions_lstm[:, 1] if x > 0.5]
    non_positive_lstm = [1 for x in predictions_lstm[:, 1] if x < 0.5]

    pos_ratio = sum(positive_lstm)/predictions_lstm.shape[0])

    pos_ratio.to_gbq(destination_table = 'sentiment_ratio', project_id = 'bigdata6893-328419', if_exist = 'append')
